### ISSUE TITLE
Question about output names of gRNAs

### ISSUE THREAD

**Issue by FabianDK** [LihuaJulieZhu/CRISPRseek#1]
Hello,

I was wondering if you could give some details on the output gRNA naming. I first thought the number in the name, e.g. 'gR47F', corresponds to the start position of the gRNA in the query sequence, but that is not the case. It more looks like it is the place of the predicted cut-site.

Thanks!

**Comment by LihuaJulieZhu** [comment]
Hi Daniel,

I am very sorry for having missed your comments!

Yes, you were right about the output gRNA naming convention. It is the place of the predicted cut-site.

For your future reference, it would be great to post your questions at https://support.bioconductor.org.

Thanks!

Best regards,
Julie
