### ISSUE TITLE
PAM position in gRNAsPlusPAM column

### ISSUE THREAD

**Issue by FabianDK** [LihuaJulieZhu/CRISPRseek#2]
Hello!

I was screening for off-targets using gRNA sequences desgined to target a transgene that normally does not occur in my organism.
In the summary.xls, I realized that when a gRNA is not found in the genome at all, then the PAM sequence in the gRNAsPlusPAM column is automatically put to the 3prime end, despite specifying the location to be 5prime.

I also think that for gRNAs not found at all, it would be useful to also show 'perfect match not found'.

Here is my code:

`offTargetAnalysis(inputFilePath = gRNAs.input,
                  findPairedgRNAOnly = FALSE, 
                  findgRNAs = FALSE,
                  BSgenomeName = BSgenome.Assembly.v1, 
                  txdb = txdb.Assembly,  
                  orgAnn = org.Assembly.eg.db,
                  outputDir = outpath, 
                  overwrite = TRUE,
                  chromToSearch = 'all',
                  max.mismatch = 3,
                  PAM = "TTN",
                  PAM.pattern = "^TTN",
                  PAM.location = '5prime',
                  n.cores.max=6)`

Output:

names | gRNAsPlusPAM | top5OfftargetTotalScore | top10OfftargetTotalScore | top1Hit.onTarget.MMdistance2PAM | topOfftarget1MMdistance2PAM | topOfftarget2MMdistance2PAM | topOfftarget3MMdistance2PAM | topOfftarget4MMdistance2PAM | topOfftarget5MMdistance2PAM | topOfftarget6MMdistance2PAM | topOfftarget7MMdistance2PAM | topOfftarget8MMdistance2PAM | topOfftarget9MMdistance2PAM | topOfftarget10MMdistance2PAM | REname
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
guide1 | TTNACCGGGGTGGTGCCCATCCT | 2.1 | 2.1 | perfect match not found | 2,4,13 | 3,10,13 | 4,10,18 |   |   |   |   |   |   |   | BccI BtsCI
guide2 | AGCGTGTCCGGCGAGGGCGATTN | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA
guide3 | TTNATCTGCACCACCGGCAAGCT | 2 | 2.2 | perfect match not found | 1,12,13 | 3,13,17 | 5,12,15 | 5,12,18 | 2,14,20 | 6,13,15 | 13,16,18 | 12,14,16 |   |   | AluI Cac8I CviKI-1 MspJI
guide4 | CGTCGCCGTCCAGCTCGACCTTN | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA
guide5 | TTNAGGGTCAGCTTGCCGTAGGT | 1.1 | 1.1 | perfect match not found | 2,3,15 | 10,13,19 | 13,14,18 |   |   |   |   |   |   |   | MspJI

**Comment by LihuaJulieZhu** [comment]
Hi Daniel,

Thank you very much for the feed back!
To help me replicate your results, could you please share your input file gRNAs.input?

For your future reference, it would be great if you could post your questions at https://support.bioconductor.org.

Thanks!

Best regards,
Julie

**Comment by hukai916** [comment]
Hi @FabianDK ,

Sorry for the late response, I can not seem to replicate your issue with the latest version of CRISRPseek. I noticed that you set `findgRNAs = FALSE` , by doing so, the gRNAs in your `gRNAs.input` will be directly used for searching off targets. It assumes that the `gRNAs.input` contain both gRNA and its PAM. If PAM not found in `gRNAs.input`, it will be added according to `PAM` and `PAM.location`. Anyway, thanks for bring this issue up!

--Kai
