### ISSUE TITLE
Error when designing gRNAs to a DNA sequence not contained in the genome.

### ISSUE THREAD

**Issue by mheydasch** [LihuaJulieZhu/CRISPRseek#8]
Line 1095 
```
rep("perfect match not found", length(gRNAs))
```
 in the file offTargetAnalysis.R throws the following error when the input DNA sequence is not contained in the genome:
```
Error in `$<-.data.frame`(`*tmp*`, "top1Hit.onTarget.MMdistance2PAM",  replacement has 263 rows, data has 7
```
This error can be easily fixed by changing the line to
```
rep("perfect match not found", length(gRNAs.notInGenome))
```

After this fix, this line uses the same length dependency as all other columns in the data frame and should therefore not throw any similar errors caused by other issues.

**Comment by carberoc** [comment]
Hi,

I had the same issue, but I could solve it thanks to your instructions. However, the off-target analysis is still not done on all the sequences from my multifasta input (they are all sequences not included in the reference genome of S. cerevisiae). Do you know why this may be happening?

**Comment by hukai916** [comment]
Hi @mheydasch ,

Thanks for spotting this issue, I have incorporated your suggestion into the dev version, which will be reflected soon in a future release. BTW, when referring to a specific line of code, I suggest to use [permlink](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-a-permanent-link-to-a-code-snippet).

--Kai
