### ISSUE TITLE
When designing gRNAs with 4 bp long PAMsites the last base of the PAM site in included in the 20bp long gRNA

### ISSUE THREAD

**Issue by mheydasch** [LihuaJulieZhu/CRISPRseek#9]
efficacy.algo = 'DeepCpf1' 
Tested with multiple PAM-sites like YTTC, YTTV, TTTN. 
The output in the summary file, will double the last letter of the PAM site. 
As an example a gRNA like TTTNCACTGCTGCGCATATGGGCT will get designed, when the actual target sequence is  TTTCACTGCTGCGCATATGGGCT. The last character of the PAM-site will not be ignored in finding correct gRNAs, but it will incorporated in both the PAM site, as well as the spacer sequence, effectively being doubled. Removing this character from the gRNA will effectively result in a too short, 19bp long gRNAs instead.
This is not just an issue with how the output is displayed, but the gRNA instead is generated with incorrect assumptions. 
As an example generating the same gRNA as above with the PAM sequence TTTC instead of TTTN will result in the gRNA TTTCCACTGCTGCGCATATGGGCTA, which will display different off target scores and efficacy values.

**Comment by LihuaJulieZhu** [comment]
Thanks for the feedback!

Could you please share your R command? Did you set PAM.size?

Best regards,
Julie

**Comment by hukai916** [comment]
Hi @mheydasch ,

I tried to replicate the double last PAM character issue you encountered. Like @LihuaJulieZhu pointed out, you may left `PAM.size` unset, which led the function to use the default value 3. This creates a discrepancy between `PAM.size` and the actual length of specified `PAM`, which caused the issue.  Setting `PAM.size = 4, PAM = "TTTN"` effectively solves the problem. I have set the default value of `PAM.size` to `width(PAM)` to avoid such problem in the devel branch, which will be reflected in next release. I am closing this issue unless you have further questions. Thanks!

--Kai
